title: Abhishek's DevLog
description: >- # this means to ignore newlines until "baseurl:"
  Abhishek's personal programming blog. The Only Official One. Filled with posts and content that explain how
  he overcame the all new project setups, errors or learnt a new technique
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://abhishekalai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: abhishek_alai
github_username:  abhishekalai

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
